server:
  http_port: 8080
  grpc_port: 50051
  host: "192.168.18.112"

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "199897"
  dbname: "file_trans"

storage:
  path: "./uploads"
  max_size: 104857600  # 100MB in bytes

cors:
  allowed_origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
    - "http://192.168.18.112:5173"
    - "http://59.110.46.76:8081"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
minio:
  endpoint: "localhost:9000"
  access_key_id: "admin"
  secret_access_key: "199897"
  use_ssl: false
  pool_size: 10
  max_idle_conns: 5
