CREATE TABLE t_file_meta (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
    file_name VARCHAR(512) NOT NULL DEFAULT '' COMMENT '文件名',
    file_size BIGINT NOT NULL DEFAULT '0' COMMENT '文件大小',
    owner VARCHAR(32) NOT NULL DEFAULT '' COMMENT '文件所有人',
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deleted_at DATETIME,
	INDEX file_name_idx (file_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件元数据表';
